### ISSUE TITLE
Detect "spot of interest"/interesting image part 

### ISSUE THREAD

**Issue by rugk** [Taiko2k/Avvie#14]
## Currently

At startup/file loading you always show a 545x545 (why this size BTW? How did you came up with that not even number – 512 would be the nearest round number :stuck_out_tongue_winking_eye:  ) rectangle at the top left.

## Improvement

IMHO you could try to use some image processing to detect a "sweet spot" or however that may be called of an image, which is interesting and could be the thing the user wants to crop.
After all, this is supposed to be easier than GIMP. :wink:

If you want, use some AI or whatever fun thing you wanna play with for that. :stuck_out_tongue_winking_eye:  

## Alternatives

Could we at leaast/maybe center the cropping? Though I'm not sure what kind of cropping happens more often. :slightly_smiling_face: 

## Relevant notes
E.g. Twitter tries to do this in their image previews, mostly just focusing on faces.

**Comment by Taiko2k** [comment]
> At startup/file loading you always show a 545x545 (why this size BTW? How did you came up with that not even number – 512 would be the nearest round number stuck_out_tongue_winking_eye ) rectangle at the top left.

The initial crop size isn't defined as a set pixel size, its defined as a proportion to the size of the source image. (Imagine, with a 10000x10000 image, if the crop size was 512 that would be relatively too tiny) 

> If you want, use some AI  / Could we at leaast/maybe center the cropping? 

I don't think it makes much difference where the initial crop is placed since its expected that the user will move it anyway. Placing it in the top corner is just fine for that IMO. Its not worth the added complexity to the application for anything more than that. Also, due to Fitts's Law, I might even argue that it is in fact not desirable to have the initial location close to the desired location.

On another note, I currently don't have the time to actively work on feature changes for this app. It's sort of in "maintenance only" mode for me.
