### ISSUE TITLE
Custom dimensions (ratio and pixel resolution)

### ISSUE THREAD

**Issue by stpnwf** [Taiko2k/Avvie#15]
I would suggest a custom button be added where the user has the option to either type a custom ratio (4:3, 20:9, etc ) or a size in pixels (1,546 x 423 pixels, etc)

Case for custom ratios: It is currently hard to crop to 20:9, 9:16, 4:3 and other ratios that are not the ones available in the app.
Case for custom pixel resolution: Useful when users need image crops that have weird ratios, such as banners for websites.

**Comment by maniaxuk** [comment]
Posting to add my support for custom dimensions

I'm trying to create a collection of cropped images to be used with superpaper (wallpaper manager) to span across a laptop screen + an external monitor the combined resolution of which is 3286x1080

Avvie seemed like the perfect tool to quickly export crops from much larger images (sometimes multiple crops from the same source image) except for the fact that each time I load a new source image the size of the crop resets which is...annoying to say the least especially as some of the source images I want to use are very large which makes using the free rectangle option very clumsy as the crop size jumps by 100's of pixels with the slightest mouse movement

Having a user definable crop size (that can be set as the default) seems like a no brainer to be honest as it would cater for ANY size rather than the select few predefined sizes Avvie currently knows about


*****

As an alternative (temporary) work around...

Where are the predefined dimensions stored?

Are they in an easily editable file?

I'm happy to have a rummage through a config file to change one of the predefined sizes to meet my needs, as long as the displayed crop overlay and resulting cropped images are correct I don't care if the labels in the application aren't right

**Comment by Taiko2k** [comment]
There's currently no way to edit the built in ratios as they're hard coded. I'll take a look at resolving these issues sometime before the upcoming version 2.0 release.

**Comment by Taiko2k** [comment]
Okay I've now committed the following changes:

 - The crop selection will (try) stay the size same when loading a new image.
 - There is now an option to enter a custom aspect ratio or resolution. (e.g. you can type `4:3` or `400x300`)
    ![Screenshot from 2022-03-01 13-52-29-cropped](https://user-images.githubusercontent.com/17271572/156263601-eabd57cb-f7f9-4275-a9da-16ae9d365ef6.jpg)



Btw I plan to make a new release version of Avvie which will include these changes later this month.
